ext.kotlin_version = "1.6.0"

allprojects {
    buildscript {
        repositories {
            google()
            mavenCentral()
            maven {
                url "https://jitpack.io"
            }
            maven { url = uri("https://artifacts.applovin.com/android") }
            maven { url "https://cboost.jfrog.io/artifactory/chartboost-ads/" }
            maven { url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea" }
            maven { url "https://verve.jfrog.io/artifactory/verve-gradle-release" }
            maven { url "https://s01.oss.sonatype.org/content/groups/public" }
            maven { url 'https://repo.pubmatic.com/artifactory/public-repos' }
            maven { url "https://artifactory.bidmachine.io/bidmachine" }
            maven { url "https://repo.premiumads.net/artifactory/mobile-ads-sdk/" }

            maven {
                url 'https://maven.aliyun.com/repository/public'
            }
            maven {
                url = 'https://packages.aliyun.com/maven/repository/2315769-snapshot-4H4gQv'
                credentials {
                    username = '62f46a2501acbf842a3ac705'
                    password = 'cBNv]fE3Dhs6'
                }
            }
            maven { url "https://bitbucket.org/sdkcenter/sdkcenter/raw/release" }
        }
        dependencies {

            classpath "com.android.tools.build:gradle:8.1.3"
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.0"

            classpath 'com.google.gms:google-services:4.3.13'
            classpath 'com.google.firebase:firebase-crashlytics-gradle:2.9.5'
            classpath("com.applovin.quality:AppLovinQualityServiceGradlePlugin:5.4.2")

        }
    }
    configurations.all {
        resolutionStrategy {
            force 'androidx.datastore:datastore-preferences:1.0.0'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
